version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: "PostgreSQL"
    restart: always
    env_file:
      - "env_files/postgres.env"
    ports:
      - '5432:5432'
    volumes:
    - ./utils/init_movies_db.sql:/docker-entrypoint-initdb.d/init.sql
    - db:/var/lib/postgresql/data

volumes:
  db: